<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        // Table: guru (80 rows)
        DB::table('guru')->truncate();
        $guruData = array (
  0 => 
  array (
    'id_guru' => 101,
    'no_id' => '1151712',
    'nama_guru' => 'NUROHMAN, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => 'Bambanglipuro',
    'kabupaten' => 'Bantul',
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => 'guru-foto/iCiJYkHT1ivyidhfx575iZmyrdo85Lu8Lb77jw43.jpg',
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  1 => 
  array (
    'id_guru' => 102,
    'no_id' => '1065444',
    'nama_guru' => 'Rr. SWISTI PRITANDARI, S.Kom',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  2 => 
  array (
    'id_guru' => 103,
    'no_id' => '1335035',
    'nama_guru' => 'DIENI NUGRAHINI, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => 'Bambanglipuro',
    'kabupaten' => 'Bantul',
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  3 => 
  array (
    'id_guru' => 104,
    'no_id' => '1527314',
    'nama_guru' => 'DIAN TRI UTAMI, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  4 => 
  array (
    'id_guru' => 105,
    'no_id' => '1306292',
    'nama_guru' => 'MUHAMMAD RIDWAN, S.Psi',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  5 => 
  array (
    'id_guru' => 106,
    'no_id' => '907793',
    'nama_guru' => 'HARIMAWAN, S.Pd.T., M.S.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  6 => 
  array (
    'id_guru' => 108,
    'no_id' => '952753',
    'nama_guru' => 'HANDRI SULISTYO, M.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  7 => 
  array (
    'id_guru' => 110,
    'no_id' => '788091',
    'nama_guru' => 'ISMAWATI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  8 => 
  array (
    'id_guru' => 111,
    'no_id' => '951752',
    'nama_guru' => 'ALWAN EFFENDI, M.S.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'ya',
    'status' => 'aktif',
    'foto' => 'guru-foto/BTpy8LMhDsjKaq7iZ3hZIblLi7eOriGrkHMoudYf.jpg',
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  9 => 
  array (
    'id_guru' => 112,
    'no_id' => '1045521',
    'nama_guru' => 'ARDIK SUDARMAJI, S.T',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  10 => 
  array (
    'id_guru' => 113,
    'no_id' => '952739',
    'nama_guru' => 'HENI PURWANTARI UTAMI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  11 => 
  array (
    'id_guru' => 114,
    'no_id' => '952755',
    'nama_guru' => 'RADEN NANANG WIRATNA, M.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  12 => 
  array (
    'id_guru' => 115,
    'no_id' => '952758',
    'nama_guru' => 'EKO SRI PURWANTO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  13 => 
  array (
    'id_guru' => 116,
    'no_id' => '1046251',
    'nama_guru' => 'BUDI SULISTIYO, S.T',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  14 => 
  array (
    'id_guru' => 117,
    'no_id' => '913672',
    'nama_guru' => 'MUHAMMAD SUPANTO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  15 => 
  array (
    'id_guru' => 118,
    'no_id' => '800389',
    'nama_guru' => 'SITI ROKHAYATI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  16 => 
  array (
    'id_guru' => 119,
    'no_id' => '952741',
    'nama_guru' => 'TRI WAHYUNI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  17 => 
  array (
    'id_guru' => 120,
    'no_id' => '952746',
    'nama_guru' => 'SAGIMAN, S.Pd.T',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  18 => 
  array (
    'id_guru' => 121,
    'no_id' => '1023697',
    'nama_guru' => 'IRHAM KURNIAWAN, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  19 => 
  array (
    'id_guru' => 122,
    'no_id' => '944058',
    'nama_guru' => 'HIKMAH ISNURANI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  20 => 
  array (
    'id_guru' => 123,
    'no_id' => '843280',
    'nama_guru' => 'WIJI MARWANTA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  21 => 
  array (
    'id_guru' => 124,
    'no_id' => '935680',
    'nama_guru' => 'Rr. SITI FATIMAH, M.S.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'ya',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  22 => 
  array (
    'id_guru' => 125,
    'no_id' => '1045931',
    'nama_guru' => 'DIAN RETNANING ASTUTI, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  23 => 
  array (
    'id_guru' => 126,
    'no_id' => '840191',
    'nama_guru' => 'IDA NURYANTI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  24 => 
  array (
    'id_guru' => 127,
    'no_id' => '884141',
    'nama_guru' => 'SARJANA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  25 => 
  array (
    'id_guru' => 128,
    'no_id' => '1047466',
    'nama_guru' => 'AGUS HARIYANTO, A.Md',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  26 => 
  array (
    'id_guru' => 130,
    'no_id' => '1045527',
    'nama_guru' => 'PANGAYOMAN, S.Sn',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  27 => 
  array (
    'id_guru' => 131,
    'no_id' => '1045529',
    'nama_guru' => 'ANI RUSMIYATI, M.S.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  28 => 
  array (
    'id_guru' => 133,
    'no_id' => '1065852',
    'nama_guru' => 'FRANDINO ARY PUTRANTO, S.Pd.Jas',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  29 => 
  array (
    'id_guru' => 134,
    'no_id' => '1045932',
    'nama_guru' => 'TASWANTO, S.Kom',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  30 => 
  array (
    'id_guru' => 135,
    'no_id' => '1045926',
    'nama_guru' => 'SRI SEKAR WIRANINGRUM, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  31 => 
  array (
    'id_guru' => 136,
    'no_id' => '932194',
    'nama_guru' => 'ENDAH SOFFIATI, S.Si',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  32 => 
  array (
    'id_guru' => 137,
    'no_id' => '1045531',
    'nama_guru' => 'ROKHMAT ZAINURI, S.Si',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  33 => 
  array (
    'id_guru' => 138,
    'no_id' => '905284',
    'nama_guru' => 'RINI PRATIWI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  34 => 
  array (
    'id_guru' => 139,
    'no_id' => '1038672',
    'nama_guru' => 'SLAMET RAHARJO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  35 => 
  array (
    'id_guru' => 140,
    'no_id' => '1030547',
    'nama_guru' => 'SUTANTININGSIH, S.Si',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  36 => 
  array (
    'id_guru' => 142,
    'no_id' => '926238',
    'nama_guru' => 'AKHMAD HANAFI, M.S.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'ya',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  37 => 
  array (
    'id_guru' => 143,
    'no_id' => '1108079',
    'nama_guru' => 'ARIF FATKHUROHMAN, S.Pd.Kor',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  38 => 
  array (
    'id_guru' => 144,
    'no_id' => '1088021',
    'nama_guru' => 'ANNISA RIZKI AMELIA, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  39 => 
  array (
    'id_guru' => 145,
    'no_id' => '881890',
    'nama_guru' => 'ARIS WARDANI, S.E',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  40 => 
  array (
    'id_guru' => 146,
    'no_id' => '1097010',
    'nama_guru' => 'EKAYANTI RETNANINGSIH, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  41 => 
  array (
    'id_guru' => 147,
    'no_id' => '868488',
    'nama_guru' => 'NASMIZARTIAN, S.Th.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  42 => 
  array (
    'id_guru' => 148,
    'no_id' => '1045533',
    'nama_guru' => 'SIGIT PURNAWAN, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  43 => 
  array (
    'id_guru' => 149,
    'no_id' => '1103434',
    'nama_guru' => 'JONI TRI SETYAWAN, S.Pd.T',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  44 => 
  array (
    'id_guru' => 150,
    'no_id' => '1134457',
    'nama_guru' => 'TUNGGAL WINATA, S.Kom',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  45 => 
  array (
    'id_guru' => 151,
    'no_id' => '856932',
    'nama_guru' => 'SARWONO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  46 => 
  array (
    'id_guru' => 152,
    'no_id' => '1165371',
    'nama_guru' => 'MUHAMMAD KHAIRIL ANWAR, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  47 => 
  array (
    'id_guru' => 153,
    'no_id' => '1151180',
    'nama_guru' => 'NOVI HIDAYAT, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  48 => 
  array (
    'id_guru' => 154,
    'no_id' => '1176839',
    'nama_guru' => 'FERA ARDI WIBOWO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  49 => 
  array (
    'id_guru' => 155,
    'no_id' => '1188869',
    'nama_guru' => 'DYAH NOVIYANITA, S.Pd',
    'jenkel' => 'P',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  50 => 
  array (
    'id_guru' => 156,
    'no_id' => '1190229',
    'nama_guru' => 'ESWANTINI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  51 => 
  array (
    'id_guru' => 157,
    'no_id' => '1156188',
    'nama_guru' => 'LISTYO BUDIARTO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  52 => 
  array (
    'id_guru' => 158,
    'no_id' => '1214077',
    'nama_guru' => 'RM.TEJA BIRAWA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  53 => 
  array (
    'id_guru' => 159,
    'no_id' => '1162434',
    'nama_guru' => 'ABDULLAH DIAN FEBRIANTA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  54 => 
  array (
    'id_guru' => 160,
    'no_id' => '1239654',
    'nama_guru' => 'TONO PRIHATIN, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  55 => 
  array (
    'id_guru' => 161,
    'no_id' => '1245495',
    'nama_guru' => 'AGUNG WIDADI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  56 => 
  array (
    'id_guru' => 162,
    'no_id' => '1305784',
    'nama_guru' => 'TANINDRA WIJANANTO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  57 => 
  array (
    'id_guru' => 163,
    'no_id' => '1303680',
    'nama_guru' => 'SAID FATHUL MAJID, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  58 => 
  array (
    'id_guru' => 164,
    'no_id' => '1305416',
    'nama_guru' => 'ROSITA DWI NOEGRAHAENI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  59 => 
  array (
    'id_guru' => 165,
    'no_id' => '1304960',
    'nama_guru' => 'USWATUN HASANAH, S.Pd.I',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'ya',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  60 => 
  array (
    'id_guru' => 166,
    'no_id' => '1316800',
    'nama_guru' => 'SURATIJO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  61 => 
  array (
    'id_guru' => 167,
    'no_id' => '1227318',
    'nama_guru' => 'MUZLIFATUL ULFAH, M.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  62 => 
  array (
    'id_guru' => 168,
    'no_id' => '1347603',
    'nama_guru' => 'NURAISYAH SULIDEWI, M.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  63 => 
  array (
    'id_guru' => 169,
    'no_id' => '1354999',
    'nama_guru' => 'RAHMAD NOVI WIBAWA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  64 => 
  array (
    'id_guru' => 170,
    'no_id' => '1404996',
    'nama_guru' => 'ERI SETYAWAN, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  65 => 
  array (
    'id_guru' => 171,
    'no_id' => '1383446',
    'nama_guru' => 'MUHAMMAD IQBAL RASYID, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'ya',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  66 => 
  array (
    'id_guru' => 172,
    'no_id' => '1421399',
    'nama_guru' => 'MUHAMMAD RIDWAN SULTHONI, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  67 => 
  array (
    'id_guru' => 174,
    'no_id' => '1045929',
    'nama_guru' => 'USFATUN KASANAH, S.Kom',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  68 => 
  array (
    'id_guru' => 175,
    'no_id' => '1511294',
    'nama_guru' => 'TUBAGUS MUTASINDRA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  69 => 
  array (
    'id_guru' => 176,
    'no_id' => '1572443',
    'nama_guru' => 'ANJAR EKO WIBOWO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  70 => 
  array (
    'id_guru' => 177,
    'no_id' => '1571459',
    'nama_guru' => 'DEVAN ALFIANTO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  71 => 
  array (
    'id_guru' => 178,
    'no_id' => '1573554',
    'nama_guru' => 'RULLY MAL AZIZ, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  72 => 
  array (
    'id_guru' => 179,
    'no_id' => '1590989',
    'nama_guru' => 'DANI KUSUMA WARDANA, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  73 => 
  array (
    'id_guru' => 180,
    'no_id' => '1581575',
    'nama_guru' => 'SHEILA AJENG ARWINANDA, S.Psi',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'ya',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  74 => 
  array (
    'id_guru' => 181,
    'no_id' => '100000',
    'nama_guru' => 'HENDRIAN NUGROHO, S.Pd',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  75 => 
  array (
    'id_guru' => 182,
    'no_id' => '667811',
    'nama_guru' => 'AGUS TRIAWANTO, S.PD',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  76 => 
  array (
    'id_guru' => 183,
    'no_id' => '1636820',
    'nama_guru' => 'PRIMA NANDA FATKHURAHMAN',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  77 => 
  array (
    'id_guru' => 184,
    'no_id' => '1680681',
    'nama_guru' => 'MUHAMMAD LUTHFI FAUZI',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  78 => 
  array (
    'id_guru' => 185,
    'no_id' => '1669114',
    'nama_guru' => 'YOGA WIDIAPRIANTO',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
  79 => 
  array (
    'id_guru' => 186,
    'no_id' => '1130041',
    'nama_guru' => 'RATNA SARI DEWI, S.PD',
    'jenkel' => 'L',
    'no_hp' => NULL,
    'kecamatan' => NULL,
    'kabupaten' => NULL,
    'guru_bk' => 'tidak',
    'guru_ismuba' => 'tidak',
    'status' => 'aktif',
    'foto' => NULL,
    'password' => '$2y$12$7xBU4Q8MW37.MYEDudOCQevk0OGCofUwV0hh05FOsYZfiw0aclIhS',
  ),
);

        foreach (array_chunk($guruData, 200) as $chunk) {
            DB::table('guru')->insert($chunk);
        }

        Schema::enableForeignKeyConstraints();
    }
}